# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: File Cloud
  description: File Cloud API of student's project (Object Oriented Programming Class - Applied Computer Science KIS AGH)
  version: "1.0.0"
# the domain of the service
host: localhost
# array of all schemes that your API supports
schemes:
  - http
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
  - application/xml
paths:
  /files/list_folder_content:
    get:
      summary: Folder's content
      description: |
        The List Folder Content endpoint returns information about the content of the specified
        folder. 
      parameters:
        - name: path
          in: query
          description: Path of the folder to be listed. Must match regex "(/\S+)"
          required: true
          type: string
          format: path
        - name: recursive
          in: query
          description: If true result will contain content of all folders within path
          required: true
          type: boolean
      tags:
        - Files
      responses:
        200:
          description: A FolderContent object
          schema:
            $ref: '#/definitions/FolderContent'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /files/upload:
    put:
      summary: Uploads file
      description: |
        The Upload endpoint listens for uploaded files.
      parameters:
        - name: path
          in: query
          description: Path of the file where data should be stored.
          required: true
          type: string
      tags:
        - Files
      responses:
        200:
          description: A FileMetadata object representing uploaded file
          schema:
            $ref: '#/definitions/FileMetadata'
  /estimates/price:
    get:
      summary: Price Estimates
      description: |
        The Price Estimates endpoint returns an estimated price range
        for each product offered at a given location. The price estimate is
        provided as a formatted string with the full price range and the localized
        currency symbol.<br><br>The response also includes low and high estimates,
        and the [ISO 4217](http://en.wikipedia.org/wiki/ISO_4217) currency code for
        situations requiring currency conversion. When surge is active for a particular
        product, its surge_multiplier will be greater than 1, but the price estimate
        already factors in this multiplier.
      parameters:
        - name: start_latitude
          in: query
          description: Latitude component of start location.
          required: true
          type: number
          format: double
        - name: start_longitude
          in: query
          description: Longitude component of start location.
          required: true
          type: number
          format: double
        - name: end_latitude
          in: query
          description: Latitude component of end location.
          required: true
          type: number
          format: double
        - name: end_longitude
          in: query
          description: Longitude component of end location.
          required: true
          type: number
          format: double
      tags:
        - Estimates
      responses:
        200:
          description: An array of price estimates by product
          schema:
            type: array
            items:
              $ref: '#/definitions/PriceEstimate'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /me:
    get:
      summary: User Profile
      description: The User Profile endpoint returns information about the Uber user that has authorized with the application.
      tags:
        - User
      responses:
        200:
          description: Profile information for a user
          schema:
            $ref: '#/definitions/Profile'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /history:
    get:
      summary: User Activity
      description: The User Activity endpoint returns data about a user's lifetime activity with Uber. The response will include pickup locations and times, dropoff locations and times, the distance of past requests, and information about which products were requested.<br><br>The history array in the response will have a maximum length based on the limit parameter. The response value count may exceed limit, therefore subsequent API requests may be necessary.
      parameters:
        - name: offset
          in: query
          type: integer
          format: int32
          description: Offset the list of returned results by this amount. Default is zero.
        - name: limit
          in: query
          type: integer
          format: int32
          description: Number of items to retrieve. Default is 5, maximum is 100.
      tags:
        - User
      responses:
        200:
          description: History information for the given user
          schema:
            $ref: '#/definitions/Activities'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  FolderMetadata:
    type: object
    properties:
      folder_id:
        type: integer
        format: int64
        description: id of the resouce
      name:
        type: string
        description: printable name of this folder
      path_lower:
        type: string
        description: path to this resource
      path_display:
        type: string
        description: printable version of path to this resource
      parent_folder_id:
        type: integer
        format: int64
        description: id of the parent folder
      server_created_at:
        type: string
        description: format="%Y-%m-%dT%H:%M:%SZ" date and time of creation of the file in the server side see https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14
  FileMetadata:
    type: object
    properties:
      file_id:
        type: integer
        format: int64
        description: id of the resouce
      name:
        type: string
        description: printable name of this folder
      path_lower:
        type: string
        description: path to this resource
      path_display:
        type: string
        description: printable version of path to this resource
      enclosing_folder_id:
        type: integer
        format: int64
        description: id of the folder directly containing this file
      size:
        type: integer
        format: int64
        description: file size in bytes
      server_created_at:
        type: string
        description: format="%Y-%m-%dT%H:%M:%SZ" date and time of creation of the file in the server side see https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14
      server_changed_at:
        type: string
        description: format="%Y-%m-%dT%H:%M:%SZ" date and time of last modification of the file in the server side see https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14
  FolderContent:
    type: object
    properties:
      folders:
        type: array
        items:
          $ref: '#/definitions/FolderMetadata'
        description: Metadata of folders included
      files:
        type: array
        items:
          $ref: '#/definitions/FileMetadata'
        description: Metadata of files included  
  PriceEstimate:
    type: object
    properties:
      product_id:
        type: string
        description: Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles
      currency_code:
        type: string
        description: "[ISO 4217](http://en.wikipedia.org/wiki/ISO_4217) currency code."
      display_name:
        type: string
        description: Display name of product.
      estimate:
        type: string
        description: Formatted string of estimate in local currency of the start location. Estimate could be a range, a single number (flat rate) or "Metered" for TAXI.
      low_estimate:
        type: number
        description: Lower bound of the estimated price.
      high_estimate:
        type: number
        description: Upper bound of the estimated price.
      surge_multiplier:
        type: number
        description: Expected surge multiplier. Surge is active if surge_multiplier is greater than 1. Price estimate already factors in the surge multiplier.
  Profile:
    type: object
    properties:
      first_name:
        type: string
        description: First name of the Uber user.
      last_name:
        type: string
        description: Last name of the Uber user.
      email:
        type: string
        description: Email address of the Uber user
      picture:
        type: string
        description: Image URL of the Uber user.
      promo_code:
        type: string
        description: Promo code of the Uber user.
  Activity:
    type: object
    properties:
      uuid:
        type: string
        description: Unique identifier for the activity
  Activities:
    type: object
    properties:
      offset:
        type: integer
        format: int32
        description: Position in pagination.
      limit:
        type: integer
        format: int32
        description: Number of items to retrieve (100 max).
      count:
        type: integer
        format: int32
        description: Total number of items available.
      history:
        type: array
        items:
          $ref: '#/definitions/Activity'
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
