# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: File Cloud
  description: File Cloud API of student's project (Object Oriented Programming Class - Applied Computer Science KIS AGH)
  version: "1.0.0"
# the domain of the service
host: localhost:4567
# array of all schemes that your API supports
schemes:
  - http
  - https
# will be prefixed to all paths
#basePath: /v1
consumes:
  - application/json
produces:
  - application/json
paths:
  /files/list_folder_content:
    get:
      tags:
        - Files
      summary: Folder's content as metadata
      description: |
        The List Folder Content endpoint returns information about the content of the specified
        folder. 
      parameters:
        - name: path
          in: query
          description: Path of the folder to be listed. Must match regex "(/\S+)"
          required: true
          type: string
          format: path
        - name: recursive
          in: query
          description: If true result will contain content of all folders within path
          required: true
          type: boolean
      responses:
        200:
          description: A FolderContent object
          schema:
            $ref: '#/definitions/FolderContent'
        404:
          description: Folder (Path) does not exist
        405:
          description: Invalid path parameter (mismatched pattern)
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /files/upload:
    post:
      tags:
        - Files
      summary: Uploads file
      description: |
        The Upload endpoint listens for uploaded files.
      parameters:
        - name: path
          in: query
          description: Path of the file where data should be stored.
          required: true
          type: string

      responses:
        200:
          description: A FileMetadata object representing uploaded file
          schema:
            $ref: '#/definitions/FileMetadata'
        405:
          description: Invalid path parameter
  /files/download:
    get:
      tags:
        - Files
      summary: Downloads file
      description: |
        The Download endpoint enables downloading of files.
      parameters:
        - name: path
          in: query
          description: Path of the file where data should be stored.
          required: true
          type: string
      responses:
        200:
          description: A FileMetadata object representing uploaded file
          headers:
            X-File-Metadata:
              type: string
#                $ref: '#/definitions/FileMetadata'
          schema:
            type: file
            #$ref: '#/definitions/FileMetadata'
        405:
          description: Invalid path parameter
  
definitions:
  FolderMetadata:
    type: object
    properties:
      folder_id:
        type: integer
        format: int64
        description: id of the resouce
      name:
        type: string
        description: printable name of this folder
      path_lower:
        type: string
        description: path to this resource
      path_display:
        type: string
        description: printable version of path to this resource
      parent_folder_id:
        type: integer
        format: int64
        description: id of the parent folder
      server_created_at:
        type: string
        description: format="%Y-%m-%dT%H:%M:%SZ" date and time of creation of the file in the server side see https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14
  FileMetadata:
    type: object
    properties:
      file_id:
        type: integer
        format: int64
        description: id of the resouce
      name:
        type: string
        description: printable name of this folder
      path_lower:
        type: string
        description: path to this resource
      path_display:
        type: string
        description: printable version of path to this resource
      enclosing_folder_id:
        type: integer
        format: int64
        description: id of the folder directly containing this file
      size:
        type: integer
        format: int64
        description: file size in bytes
      server_created_at:
        type: string
        description: format="%Y-%m-%dT%H:%M:%SZ" date and time of creation of the file in the server side see https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14
      server_changed_at:
        type: string
        description: format="%Y-%m-%dT%H:%M:%SZ" date and time of last modification of the file in the server side see https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14
  FolderContent:
    type: object
    properties:
      folders:
        type: array
        items:
          $ref: '#/definitions/FolderMetadata'
        description: Metadata of folders included
      files:
        type: array
        items:
          $ref: '#/definitions/FileMetadata'
        description: Metadata of files included  
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
